name: 'Unity - Test runner'
author: Webber Takken <webber@takken.io>
description: 'Run tests for any Unity project.'
inputs:
  unityVersion:
    required: false
    default: '2019.2.11f1'
    description: 'Version of unity to use for testing the project.'
outputs:
  artifactsPath:
    description: 'Path where the artifacts are stored'
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'action/index.js'
